/*
Package apidoc writes docs/api.md, the signature index of this module's public
packages, and lists the exported identifiers that have no doc comment. Spec
008 R2.

It is repository plumbing shared by cmd/sanshoku-apidoc, which writes the page,
and api_test.go, which regenerates it in memory and compares. It reads the
source with go/parser and go/doc: no build, no cgo, no network. A public
package is every package in the module that is not package main and not under
internal/.

The page is an index, not a transcript. pkg.go.dev renders the prose; the index
is small enough that a pull request which widens the public surface shows it in
the diff.
*/
package apidoc

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/doc"
	"go/parser"
	"go/printer"
	"go/token"
	"go/types"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
)

// pageHead opens docs/api.md.
const pageHead = `# API reference

<!-- Generated by ` + "`make generate`" + ` from the doc comments. Do not edit; edit the
     comment and regenerate. ` + "`make check-api`" + ` and api_test.go fail on a
     diff. -->

A signature index of every public package: the package synopsis, then each
exported identifier with its signature and the first sentence of its doc
comment. A type's constants, variables, constructors and methods are listed
under it. [pkg.go.dev](https://pkg.go.dev/github.com/ushineko/sanshoku) has the
full prose.
`

// pkg is one public package, parsed and filtered to its exported surface.
type pkg struct {
	rel  string // directory relative to the module root, "" for the root
	path string // import path
	doc  *doc.Package
	fset *token.FileSet
}

// name is the package as the page and the undocumented list name it: its
// directory, or the module's last element for the root package.
func (p pkg) name() string {
	if p.rel == "" {
		return path.Base(p.path)
	}
	return p.rel
}

// Generate renders docs/api.md for the module rooted at root.
func Generate(root string) (string, error) {
	pkgs, err := load(root)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString(pageHead)
	for _, p := range pkgs {
		writePackage(&b, p)
	}
	return b.String(), nil
}

// Undocumented lists every exported identifier in a public package that has
// no doc comment, as package.Identifier or package.Type.Method.
func Undocumented(root string) ([]string, error) {
	pkgs, err := load(root)
	if err != nil {
		return nil, err
	}
	var missing []string
	for _, p := range pkgs {
		at := func(parts ...string) string {
			return strings.Join(append([]string{p.name()}, parts...), ".")
		}
		missing = append(missing, undocumentedValues(p.doc.Consts, at)...)
		missing = append(missing, undocumentedValues(p.doc.Vars, at)...)
		for _, t := range p.doc.Types {
			if strings.TrimSpace(t.Doc) == "" {
				missing = append(missing, at(t.Name))
			}
			missing = append(missing, undocumentedValues(t.Consts, at)...)
			missing = append(missing, undocumentedValues(t.Vars, at)...)
			for _, f := range t.Funcs {
				if strings.TrimSpace(f.Doc) == "" {
					missing = append(missing, at(f.Name))
				}
			}
			for _, m := range t.Methods {
				if strings.TrimSpace(m.Doc) == "" {
					missing = append(missing, at(t.Name, m.Name))
				}
			}
		}
		for _, f := range p.doc.Funcs {
			if strings.TrimSpace(f.Doc) == "" {
				missing = append(missing, at(f.Name))
			}
		}
	}
	return missing, nil
}

// undocumentedValues names the constants or variables with no comment of
// their own and no comment on their group. A trailing line comment counts, as
// it does on pkg.go.dev.
func undocumentedValues(values []*doc.Value, at func(...string) string) []string {
	var missing []string
	for _, v := range values {
		if strings.TrimSpace(v.Doc) != "" {
			continue
		}
		for _, s := range v.Decl.Specs {
			vs, ok := s.(*ast.ValueSpec)
			if !ok || vs.Doc.Text() != "" || vs.Comment.Text() != "" {
				continue
			}
			for _, n := range vs.Names {
				if n.IsExported() {
					missing = append(missing, at(n.Name))
				}
			}
		}
	}
	return missing
}

// load parses every public package under root, in import-path order.
func load(root string) ([]pkg, error) {
	module, err := modulePath(root)
	if err != nil {
		return nil, err
	}
	var pkgs []pkg
	err = filepath.WalkDir(root, func(dir string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(root, dir)
		if err != nil {
			return fmt.Errorf("relative path: %w", err)
		}
		rel = filepath.ToSlash(rel)
		if rel == "." {
			rel = ""
		}
		base := d.Name()
		if rel != "" && (strings.HasPrefix(base, ".") || base == "testdata" || rel == "internal") {
			return filepath.SkipDir
		}
		p, ok, err := parsePackage(dir, rel, module)
		if err != nil {
			return err
		}
		if ok {
			pkgs = append(pkgs, p)
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("apidoc: %w", err)
	}
	sort.Slice(pkgs, func(i, j int) bool { return pkgs[i].path < pkgs[j].path })
	return pkgs, nil
}

// parsePackage reads the non-test Go files in dir. ok is false for a
// directory with none, or for package main.
func parsePackage(dir, rel, module string) (pkg, bool, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return pkg{}, false, fmt.Errorf("read %s: %w", dir, err)
	}
	fset := token.NewFileSet()
	var files []*ast.File
	for _, e := range entries {
		n := e.Name()
		if e.IsDir() || !strings.HasSuffix(n, ".go") || strings.HasSuffix(n, "_test.go") {
			continue
		}
		f, err := parser.ParseFile(fset, filepath.Join(dir, n), nil, parser.ParseComments)
		if err != nil {
			return pkg{}, false, fmt.Errorf("parse: %w", err)
		}
		files = append(files, f)
	}
	if len(files) == 0 || files[0].Name.Name == "main" {
		return pkg{}, false, nil
	}
	importPath := module
	if rel != "" {
		importPath = module + "/" + rel
	}
	d, err := doc.NewFromFiles(fset, files, importPath)
	if err != nil {
		return pkg{}, false, fmt.Errorf("doc %s: %w", importPath, err)
	}
	return pkg{rel: rel, path: importPath, doc: d, fset: fset}, true, nil
}

// modulePath reads the module line from root's go.mod.
func modulePath(root string) (string, error) {
	b, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		return "", fmt.Errorf("apidoc: %w", err)
	}
	for _, line := range strings.Split(string(b), "\n") {
		if m, ok := strings.CutPrefix(strings.TrimSpace(line), "module "); ok {
			return strings.Trim(strings.TrimSpace(m), `"`), nil
		}
	}
	return "", errors.New("apidoc: go.mod has no module line")
}

// writePackage renders one package's section.
func writePackage(b *strings.Builder, p pkg) {
	d := p.doc
	fmt.Fprintf(b, "\n## %s\n\n`import %q`\n", p.name(), p.path)
	if s := d.Synopsis(d.Doc); s != "" {
		fmt.Fprintf(b, "\n%s\n", s)
	}
	if len(d.Consts) > 0 {
		b.WriteString("\n### Constants\n\n")
		writeValues(b, d, d.Consts)
	}
	if len(d.Vars) > 0 {
		b.WriteString("\n### Variables\n\n")
		writeValues(b, d, d.Vars)
	}
	if len(d.Types) > 0 {
		b.WriteString("\n### Types\n")
		for _, t := range d.Types {
			writeType(b, p.fset, d, t)
		}
	}
	if len(d.Funcs) > 0 {
		b.WriteString("\n### Functions\n\n")
		for _, f := range d.Funcs {
			item(b, funcSignature(f.Decl), d.Synopsis(f.Doc))
		}
	}
}

// writeType renders a type's declaration, its first sentence, and the
// constants, variables, constructors and methods go/doc files under it.
func writeType(b *strings.Builder, fset *token.FileSet, d *doc.Package, t *doc.Type) {
	fmt.Fprintf(b, "\n#### type %s\n\n```go\n%s\n```\n", t.Name, typeDecl(fset, t.Decl))
	if s := d.Synopsis(t.Doc); s != "" {
		fmt.Fprintf(b, "\n%s\n", s)
	}
	if len(t.Consts)+len(t.Vars)+len(t.Funcs)+len(t.Methods) == 0 {
		return
	}
	b.WriteString("\n")
	writeValues(b, d, t.Consts)
	writeValues(b, d, t.Vars)
	for _, f := range t.Funcs {
		item(b, funcSignature(f.Decl), d.Synopsis(f.Doc))
	}
	for _, m := range t.Methods {
		item(b, funcSignature(m.Decl), d.Synopsis(m.Doc))
	}
}

// writeValues renders each exported name in a const or var group on its own
// line, with its own comment's first sentence, or its group's.
func writeValues(b *strings.Builder, d *doc.Package, values []*doc.Value) {
	for _, v := range values {
		kw := v.Decl.Tok.String()
		var typ ast.Expr // carried down an iota group
		for _, s := range v.Decl.Specs {
			vs, ok := s.(*ast.ValueSpec)
			if !ok {
				continue
			}
			if vs.Type != nil || len(vs.Values) > 0 {
				typ = vs.Type
			}
			text := vs.Doc.Text()
			if text == "" {
				text = vs.Comment.Text()
			}
			if text == "" {
				text = v.Doc
			}
			for i, n := range vs.Names {
				if !n.IsExported() {
					continue
				}
				sig := kw + " " + n.Name
				if typ != nil {
					sig += " " + types.ExprString(typ)
				}
				if len(vs.Values) == len(vs.Names) {
					sig += " = " + types.ExprString(vs.Values[i])
				}
				item(b, sig, d.Synopsis(text))
			}
		}
	}
}

// item writes one list line: the signature, and the sentence when there is
// one.
func item(b *strings.Builder, sig, sentence string) {
	if sentence == "" {
		fmt.Fprintf(b, "- `%s`\n", sig)
		return
	}
	fmt.Fprintf(b, "- `%s`: %s\n", sig, sentence)
}

// funcSignature is a function or method's declaration on one line, without
// its body.
func funcSignature(fd *ast.FuncDecl) string {
	var b strings.Builder
	b.WriteString("func ")
	if fd.Recv != nil && len(fd.Recv.List) > 0 {
		r := fd.Recv.List[0]
		b.WriteString("(")
		if len(r.Names) > 0 {
			b.WriteString(r.Names[0].Name + " ")
		}
		b.WriteString(types.ExprString(r.Type) + ") ")
	}
	b.WriteString(fd.Name.Name)
	if tp := fd.Type.TypeParams; tp != nil && len(tp.List) > 0 {
		b.WriteString("[" + fieldList(tp.List) + "]")
	}
	b.WriteString(strings.TrimPrefix(types.ExprString(fd.Type), "func"))
	return b.String()
}

// fieldList is a parameter list without its brackets.
func fieldList(fields []*ast.Field) string {
	parts := make([]string, 0, len(fields))
	for _, f := range fields {
		names := make([]string, 0, len(f.Names))
		for _, n := range f.Names {
			names = append(names, n.Name)
		}
		s := types.ExprString(f.Type)
		if len(names) > 0 {
			s = strings.Join(names, ", ") + " " + s
		}
		parts = append(parts, s)
	}
	return strings.Join(parts, ", ")
}

// typeDecl is a type's declaration as gofmt prints it, without comments.
// go/doc has already dropped unexported fields and methods and marked where.
func typeDecl(fset *token.FileSet, decl *ast.GenDecl) string {
	var buf bytes.Buffer
	cfg := printer.Config{Mode: printer.UseSpaces | printer.TabIndent, Tabwidth: 8}
	stripped := &ast.GenDecl{Tok: decl.Tok}
	for _, s := range decl.Specs {
		stripped.Specs = append(stripped.Specs, withoutComments(s))
	}
	if len(decl.Specs) > 1 {
		stripped.Lparen, stripped.Rparen = decl.Lparen, decl.Rparen
	}
	if err := cfg.Fprint(&buf, fset, stripped); err != nil {
		return fmt.Sprintf("type %v", err)
	}
	return buf.String()
}

// withoutComments copies a type spec with its own comments and its fields'
// and methods' comments removed. The printer draws a field's comments from the
// field itself, so leaving them in would make the index a transcript.
func withoutComments(spec ast.Spec) ast.Spec {
	ts, ok := spec.(*ast.TypeSpec)
	if !ok {
		return spec
	}
	c := *ts
	c.Doc, c.Comment = nil, nil
	switch t := ts.Type.(type) {
	case *ast.StructType:
		st := *t
		st.Fields = bareFields(t.Fields)
		c.Type = &st
	case *ast.InterfaceType:
		it := *t
		it.Methods = bareFields(t.Methods)
		c.Type = &it
	}
	return &c
}

// bareFields copies a field list without the fields' comments.
func bareFields(fl *ast.FieldList) *ast.FieldList {
	if fl == nil {
		return nil
	}
	c := *fl
	c.List = make([]*ast.Field, 0, len(fl.List))
	for _, f := range fl.List {
		g := *f
		g.Doc, g.Comment = nil, nil
		c.List = append(c.List, &g)
	}
	return &c
}
